fix(hestia): hestia fails if fails to read
This happens in the contexto of --stdin, where supposedly one should feed
it from stdin, thus an empty stdin is a failure

diff --git a/hestia/hestia b/hestia/hestia
--- a/hestia/hestia
+++ b/hestia/hestia
@@ -20,7 +20,8 @@ EOH
 read_executable() {
 	local LINE
 	if ! read LINE; then
-		return
+		echo "no line read, aborting =/" >&2
+		exit 1
 	fi
 	if [ "${LINE:0:2}" = '#!' ]; then
 		echo "$LINE"
